name: CI

on:
  push:
    branches: [ main, develop, "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm build
        
      - name: Lint
        run: npm run lint --if-present

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Run tests with Firebase Emulators
        run: npm run test:emulators

      - name: Build (type-check)
        run: npm run build

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: functions/coverage
