name: Release

on:
  workflow_run:
    workflows: ["ci"]
    types: [completed]
    branches: [main]
  pull_request:
    branches: [release/stable]

jobs:
  develop:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      REFRESH_EXPIRES_IN: ${{ secrets.REFRESH_EXPIRES_IN }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
      JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build (type-check)
        run: npm run build

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Run tests with Firebase Emulators
        run: npm run test:emulators

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: functions/coverage

  deploy:
    # Solo corre cuando terminó CI en main y CI fue success
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: []   # no depende del job develop; depende del otro workflow (CI)
    defaults:
      run:
        working-directory: functions
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout the exact commit that passed CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Create .env for tests
        run: |
          cat > functions/.env <<'EOF'
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          REFRESH_EXPIRES_IN=${{ secrets.REFRESH_EXPIRES_IN }}
          EOF

      - name: Build (ensure lib/* exists)
        run: npm run build && cd src

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Functions
        run: firebase deploy --only functions -P "$PROJECT_ID" --non-interactive --token "$FIREBASE_TOKEN"
